announcement1:
  message1: This is a test1.
  delay1: 200
announcement2:
  message2: This is a test2.
  delay2: 200
announcement3:
  message3: This is a test3.
  delay3: 200
announcement4:
  message4: This is a test4.
  delay4: 200
announcement5:
  message5: This is a test5.
  delay5: 200
announcement6:
  message6: This is a test6.
  delay6: 200
announcement7:
  message7: This is a test7.
  delay7: 200
announcement8:
  message8: This is a test8.
  delay8: 200
