badwords:
  - shit
  - fuck
  - fuk
  - shite
  - motherfucker
  - motherfuker
  - suck
  - shitty
  - pussy
  - pusy
  - ass
  - asshole
  - asswhole
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 